export const text = {
  NAME: 'Vova Gridnev',
  ITS_ME: `Hello, I'm`,
  FRONTEND_DEV: 'Frontend developer',
  DOWNLOAD_CV: 'Download CV',
  CONTACT_ME: 'Contact Me',
  SCROLL_DOWN: 'Scroll Down →',
  CORGI_ALT: 'CorgiInSpace',
  TIME_TO_TELL: 'Time to tell',
  ABOUT_ME: 'About Me',
  EXPERIENCE: 'Experience',
  EXPERIENCE_DESC: 'Frontend: 1 year, SysAdm: 5 years',
  PROJECTS: 'Projects',
  PROJECTS_DESC: '10+ completed',
  EDUCATION: 'Education',
  EDUCATION_DESC: 'Moscow Polytechnic University & Yandex.Practicum',
  ABOUT_ALT: 'Corgi developer',
  MAGNIT: 'Magnit',
  ABOUT_COMPANY: 'О компании',
  TEXT_BLOCK1:
    'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium aliquam beatae cupiditate dolor dolorem earum eius expedita harum impedit incidunt magni mollitia necessitatibus officia provident quisquam reprehenderit repudiandae sed sequi tempore tenetur vel voluptas, voluptatum. Beatae fugit rerum sequi voluptates!',
  TEXT_BLOCK2:
    'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium aliquam beatae cupiditate dolor dolorem earum eius expedita harum impedit incidunt magni mollitia necessitatibus officia',
  FIRST_BLOCK_NUMBER: '1029',
  FIRST_BLOCK_NUMBER_DESC: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',
  SECOND_BLOCK_NUMBER: '432',
  SECOND_BLOCK_NUMBER_DESC: 'Lorem ipsum dolor sit amet',
  THIRD_BLOCK_NUMBER: '6663',
  THIRD_BLOCK_NUMBER_DESC:
    'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi aperiam',
  FOURTH_BLOCK_NUMBER: '11',
  FOURTH_BLOCK_NUMBER_DESC: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit',

  COPYRIGHT: '2022 Строительная компания МАГНИТ. Все права защищены',
  PHONE_NUMBER: '+7 (910) 123-45-67',
  ADDRESS: 'Адрес:',
  ADDRESS_TEXT: 'Россия, г. Краснодар, ул. Название улицы, 238, оф. 8782',
  EMAIL: 'E-mail:',
  EMAIL_TEXT: 'info@mywd-design.ru',
};
